site_name: TrustMark Glossary
site_url: https://petehitchen.github.io/trustmark-glossary/

theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - TrustMark Glossary: trustmark-glossary.md

extra_css:
  - extra.css
  - docs/extra.css     # <-- this is the real one you are editing

extra_javascript:
  - glossary.js
  - docs/glossary.js   # <-- and this is the one MkDocs will find
